---
#
# This is the canonical configuration for the `README.md`
# Run `make readme` to rebuild the `README.md`
#

# Name of this project
name: Ansible Role Docker

# License of this project
license: "MIT"

# Canonical GitHub repo
github_repo: clouddrove/ansible-role-docker

# Badges to display
badges:
  - name: "Ansible"
    image: "https://img.shields.io/badge/Ansible-2.8-green?style=flat&logo=ansible"
    url: "https://www.ansible.com"
  - name: "Licence"
    image: "https://img.shields.io/badge/License-MIT-blue.svg"
    url: "LICENSE.md"
  - name: "Distribution"
    image: "https://img.shields.io/badge/ubuntu-16.x-orange?style=flat&logo=ubuntu"
    url: "https://ubuntu.com/"
  - name: "Distribution"
    image: "https://img.shields.io/badge/ubuntu-18.x-orange?style=flat&logo=ubuntu"
    url: "https://ubuntu.com/"
  - name: "Distribution"
    image: "https://img.shields.io/badge/centos-7.x-orange"
    url: "https://www.centos.org/"

# Prerequesties to display
# yamllint disable
prerequesties:
  - name: "Ansible2.8"
    url: "https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html"
  - name: "Python"
    url: "https://www.python.org/downloads"

# yamllint enable
# What Includes to display
what_includes:
  - name: "docker"
  - name: "docker-compose"

#  description of this project
description: |-
  This ansible role install docker on linux.

# How to use this project
usage: |-
  ```yaml
  - hosts: localhost
    remote_user: root
    roles:
      - clouddrove.ansible_role_docker
  ```
# Variables use in the project
variables: |-
  ```yaml
      docker_users: ['docker']
      docker_compose_install: true
      docker_compose_version: "1.21.2"
  ```

# How to install project
installation: |-
  ```console
    $ ansible-galaxy install clouddrove.ansible_role_docker
  ```
