version: '3.1'

services:
  pg:
    image: postgres:10
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: root
    healthcheck:
      test: [ "CMD", "pg_isready", "--user=root" ]
      interval: 600s
      timeout: 10s
      retries: 3
