---
dependencies: []

galaxy_info:
  author: Anmol Nagpal
  description: This ansible role install docker at Debian and Centos.
  company: "CloudDrove Inc."
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - containers
    - docker
    - orchestration
    - server
    - ubuntu
    - centos
    - compose
